config/routes.rb
Rails.application.routes.draw do
  root 'comments#index'
  
  mount ActionCable.server => '/cable'
  
  get  'sendStyles', to: 'comments#changeStyles'
  get  'usage', to: 'comments#usage'
  get  'screen', to:'comments#screen'
  get  'youtube', to:'comments#youtube'
  get  'twitch',  to:'comments#twitch'
  
end

app/views/layouts/body_partials/_bottom.html.erb
<div class="btn-container bottom-btn-container">
  <button id="button_refresh" class="btn btn-success btn-bottom" type="button">UPDATE SETTINGS</button>
  <button id="button" class="btn btn-danger btn-bottom btn--deactive" id="button">GENERATE</button>
</div>

app/views/layouts/body_partials/_footer.html.erb
<div class="footer-content">
  <div class="wrapper footer-wrapper">
    <div class="box box-footer box-footer-right">
      <h3 class="footer-title">CONTENTS</h3>
      <ul class="">
        <li class="footer-links">
          <%= link_to "HOME", root_path %>
        </li>
        <li class="footer-links">
          <%= link_to "SCREEN", screen_path, target: "_blank", rel: "noopener noreferrer" %>
        </li>
        <li class="footer-links">
          <%= link_to "USAGE", usage_path %>
        </li>
      </ul>
    </div>
    <div class="box box-footer box-footer-right">
      <h3 class="footer-title">OTHERSITES</h3>
      <ul class="">
        <li class="footer-links">
          <%= link_to "Develop repository", 'https://github.com/n20006/GraduationTask_Team', target: "_blank", rel: "nopener noreferrer" %>
        </li>
        <li class="footer-links">
          <%= link_to "Developper github ", 'https://github.com/n20010', target: "_blank", rel: "nopener noreferrer" %>
        </li>
        <li class="footer-links">
          <%= link_to "Twitter api reference", 'https://developer.twitter.com/en/docs/api-reference-index', target: "_blank", rel: "nopener noreferrer" %>
        </li>
        <li class="footer-links">
          <%= link_to "Youtube api reference", 'https://developers.google.com/youtube/v3/docs?hl=ja', target: "_blank", rel: "nopener noreferrer" %>
        </li>
        <li class="footer-links">
          <%= link_to "Amazon web service", 'https://aws.amazon.com/jp/', target: "_blank", rel: "nopener noreferrer" %>
        </li>
        <li class="footer-links">
          <%= link_to "Ruby on Rails official", 'https://rubyonrails.org/', target: "_blank", rel: "nopener noreferrer" %>
        </li>
      </ul>
    </div>
  </div>
</div>
  <div id="footer-last">
    <h5 id="copyright">Copyright © 2021 〇〇 Inc. All Rights Reserved.</h5>  
  </div>

app/views/layouts/body_partials/_koya.html.erb
<div class="container-sm d-flex flex-column justify-content-center">
    <!-- フォーマット -->
    <div class="d-flex flex-column justify-content-center mt-3">
      <h3 class="index-label index-label-outputFormat">OUTPUT MODE</h3>

      <div class="wrapper wrapper-select-button">
        <div class="fontSize format-box">
          <div class="format-icon">
            <div>
            <input type="radio" class="radio" id="niconico" name="format" value="niconico" checked/>
            <label class='niconico-label' for="niconico"></label>
            </div>
          </div> 
          <div class="format-description">
            <h2 class='niconico-title'>niconico mode</h2>
            <p class="main-description">Generating comments like niconico</p>
            <p class="main-description">Thats will be move right to left</p>
            <p class="main-description"> You can change all settings</p>
          </div>
        </div>
        
        <div class="fontSize format-box">
          <div class="format-icon">
            <input type="radio" class="radio" id="youtube" name="format" value="youtube" />
            <label class='youtube-label' for="youtube"></label>
          </div>
          <div class="format-description">
            <h2 class='youtube-title'>YouTube mode</h2>
            <p class="main-description">Generating comments like YouTube</p>
            <p class="main-description">Thats will be move top to bottom</p>
            <p class="main-description">You can't change above settings</p>
          </div>          
        </div>
      </div>
    </div>
</div>

app/views/layouts/body_partials/_middle.html.erb
<div class="middle-wrapper">
  
  
  <div class='wrapper'>
    
    <div class="box fontSize">
      <nav class="navbar navbar-light bg-light">
        <h3 class="index-label">FONT SIZE</h3>
        <form class="container-fluid justify-content-start" style="display:block" >
          <input type="range" class="form-range" id="form-range-size" min="20" max="56" step="0.5" value="38" id="customRange3"> 
        </form>
      </nav>
    </div>
    
    <div class="box fontSize">
      <nav class="navbar navbar-light bg-light">
        <h3 class="index-label">OPACITY</h3>
        <form class="container-fluid justify-content-start" style="display:block" >
          <input type="range" class="form-range" id="form-range-opacity" min="0.2" max="1" step="0.1" value="1" id="customRange3"> 
        </form>
      </nav>
    </div>
    <!--
    <div class="box speed">
      <nav class="navbar navbar-light bg-light">
        <h3 class="index-label">SPEED</h3>
        <form class="container-fluid justify-content-start" style="display:block" >
          <div class="btn-container">
            <button class="btn btn-outline-success me-2 speed" type="button" value="遅い">SLOWLY</button>
            <button class="btn btn-outline-success me-2 speed" type="button" value="普通">DEFAULT</button>
            <button class="btn btn-outline-success me-2 speed" type="button" value="速い">FASTER</button>
          </div>
        </form>
      </nav>
    </div>
    -->
  </div>
  
</div>

<div class='box-form'>
    <%= render "layouts/body_partials/koya" %>
</div>
  
  <div class="box-form twitter">
    <div class="form-floating mb-3">
      <input type="text" class="form-control twittertag" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Twitter Keyword</label>
    </div>
    <div class="form-floating mb-3">
      <input type="text" class="form-control youtubeurl" id="floatingInput" placeholder="name@example.com">
      <label for="floatingInput">Youtube URL</label>
    </div>
  </div>

app/views/layouts/body_partials/_sidebar.html.erb
<div id="sidebar-carousel" class="sidebar-content">
  <div class="add-border">
    <div id="carouselExampleFade" class="carousel slide carousel-fade" data-bs-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img src="/images/github.png"class="d-block w-100 carousel-img" alt="...">
        </div>
        <div class="carousel-item">
          <img src="/images/twitter.jpg" class="d-block w-100 carousel-img" alt="...">
        </div>
        <div class="carousel-item">
          <img src="/images/youtube.png" class="d-block w-100 carousel-img" alt="...">
        </div>
        <div class="carousel-item">
          <img src="/images/aws.png" class="d-block w-100 carousel-img" alt="...">
        </div>
        <div class="carousel-item">
          <img src="/images/rails.png" class="d-block w-100 carousel-img" alt="...">
        </div>
        <div class="carousel-item">
          <img src="/images/okuto.jpg" class="d-block w-100 carousel-img" alt="...">
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleFade" role="button" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleFade" role="button" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
      </a>
    </div>
  </div>
</div> 
  

<div id="sidebar-cards" class="sidebar-content"> 
  <div id="cards">
    <div class="card">
      <%= link_to image_tag("/images/github.png", class:"card-img-top"), 'https://github.com/n20006/GraduationTask_Team' %>
      <div class="card-body">
        <p class="card-text">An Github repository link this web application is here. We made this app for graduation task.</p>
      </div>
    </div>
    <div class="card">
      <%= link_to image_tag("/images/twitter.jpg", class:"card-img-top"), 'https://developer.twitter.com/en/docs/api-reference-index' %>
      <div class="card-body">
        <p class="card-text">Twitter Web API is used here. If you wanna learning it's details, click here.</p>
      </div>
    </div>
    <div class="card">
      <%= link_to image_tag("/images/youtube.png", class:"card-img-top"),  'https://developers.google.com/youtube/v3/docs?hl=ja' %>
      <div class="card-body">
        <p class="card-text">Youtube Web API is used here. If you wanna learning it's details, click here.</p>
      </div>
    </div>
    <div class="card">
      <%= link_to image_tag("/images/aws.png", class:"card-img-top"),  'https://aws.amazon.com/jp/' %>
      <div class="card-body">
        <p class="card-text">AWS (Amazon Web Services) is a comprehensive, IaaS, PaaS SaaS etc... click and check any features.</p>
      </div>
    </div>
    <div class="card">
      <%= link_to image_tag("/images/rails.png", class:"card-img-top"), 'https://rubyonrails.org/' %>
      <div class="card-body">
        <p class="card-text">Ruby on Rails makes it much easier and more fun. It includes everything you need to build fantastic applications.</p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/body_partials/_top.html.erb
<div class="border div-top">
  <span class="sample generageSpanClass">HELLO WORLD</span>
</div>